<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CandidateCertificate extends Model
{
    use HasFactory;

    protected $fillable = [
        'description', 'candidate_id', 'media_id', 'country_id',
        'completion_date', 'valid_until', 'ongoing', 'name', 'category', 'institution'
    ];

    protected $appends = [
        'saving'
    ];

    protected $with = [
        'media'
    ];

    public function getSavingAttribute(){
        return false;
    }

    public function delete()
    {
        if($this->media){
            $this->media->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function media(){
        return $this->hasOne(\Spatie\MediaLibrary\Models\Media::class, 'id', 'media_id')
                    ->where('model_type', 'App\Models\Candidate')
                    ->orderBy('id', 'DESC');
    }
}
